ProvaCognos/Models/Empresa.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvaCognos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.Contato = new HashSet<Contato>();
        }
    
        public int EmpresaID { get; set; }
        public string Nome { get; set; }
        public string Telefone { get; set; }
        public string Site { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DataInclusao { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contato> Contato { get; set; }
    }
}

ProvaCognos/Controllers/EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProvaCognos.Models;

namespace ProvaCognos.Controllers
{
    public class EmpresaController : Controller
    {
        public ActionResult Index()
        {
            List<Empresa> model = EmpresaRepository.list();

            return View(model);
        }

        public ActionResult Details(int id)
        {
            var model = EmpresaRepository.get(id);

            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Empresa model)
        {
            EmpresaRepository.create(model);

            return RedirectToAction("Details", new { id = model.EmpresaID });
        }

        public ActionResult Edit(int id)
        {
            Empresa model = EmpresaRepository.get(id);

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Empresa model)
        {
            EmpresaRepository.update(model);

            return RedirectToAction("Details", new { id = model.EmpresaID });
        }

        public ActionResult Delete(int id)
        {
            EmpresaRepository.delete(id);

            return RedirectToAction("Index");
        }
    }
}

ProvaCognos/Views/Empresa/Create.cshtml
@model ProvaCognos.Models.Empresa

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>New</h2>

@using (Html.BeginForm("Create","Empresa",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Empresa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Site, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Site, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Site, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                @Html.DropDownListFor(model => model.Status,
                new List<SelectListItem> {
                            new SelectListItem { Text = ProvaCognos.Utils.StaticValues.EmpresaStatus.CADASTRADO},
                            new SelectListItem { Text = ProvaCognos.Utils.StaticValues.EmpresaStatus.EXCLUIDA},
                            new SelectListItem { Text = ProvaCognos.Utils.StaticValues.EmpresaStatus.INVALIDO},
                            new SelectListItem { Text = ProvaCognos.Utils.StaticValues.EmpresaStatus.VERIFICADO}
                })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProvaCognos/Views/Empresa/Details.cshtml
@model ProvaCognos.Models.Empresa

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Empresa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Site)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Site)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataInclusao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataInclusao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataAlteracao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataAlteracao)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EmpresaID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProvaCognos/Views/Empresa/Edit.cshtml
@model ProvaCognos.Models.Empresa

@{
    ViewBag.Title = "Edição de empresas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Empresa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EmpresaID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Site, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Site, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Site, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProvaCognos/Views/Empresa/Index.cshtml
@model IEnumerable<ProvaCognos.Models.Empresa>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Empresas";
}
<div>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
@if (Model != null)
{
    <table class="table" id="tableEmpresa">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Site)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataInclusao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataAlteracao)
            </th>
            <th></th>
        </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Telefone)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Site)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataInclusao)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataAlteracao)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.EmpresaID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.EmpresaID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.EmpresaID })
                    </td>
                </tr>
            }
    </table>
}
else
{
    <p>Ainda não existem empresas.</p>
}
</div>

@section Scripts{
    
    <script type="text/javascript">
        $(document).ready(function () {
            $('#tableEmpresa').DataTable();
        });
    </script>   
}